FROM rust AS builder

RUN apt-get update
RUN apt-get install -y build-essential cmake libclang-dev

WORKDIR /build

COPY Cargo.toml LICENSE README.md ./
COPY src src/

RUN cargo build --release

FROM ubuntu

RUN apt-get update
RUN apt-get install -y ca-certificates

WORKDIR /opt

COPY --from=builder /build/target/release/kvstore .

ENTRYPOINT ["/opt/kvstore"]