name: Build anything

on:
  workflow_call:
    inputs:
      image:
        description: "Docker image name"
        type: string
        required: true
      path:
        description: "Path to Dockerfile"
        type: string
        required: true
      build_runner:
        description: "Github runners tag"
        type: string
        required: false
        default: ubuntu-latest
    secrets:
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true

jobs:
  build:
    runs-on: ${{ inputs.build_runner }}
    outputs:
      image_version: ${{ steps.meta.outputs.version }}
      image_id: ${{ steps.build_push.outputs.imageid }}
      commit_message: ${{ steps.commit_info.outputs.message }}
      commit_hash: ${{ steps.commit_info.outputs.hash }}
      author_name: ${{ steps.commit_info.outputs.author_name }}
      author_email: ${{ steps.commit_info.outputs.author_email }}
    steps:
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ inputs.image }}
          tags: |
            type=raw,value=latest
            type=raw,value=${{ inputs.tags }}
            type=match,event=tag,pattern=\d+-\d+-\d+
      - name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        id: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Get head commit information
        id: commit_info
        run: |
          echo "message=$(git log -n 1 --format=%B HEAD | head -n 1)" >> $GITHUB_OUTPUT
          echo "hash=$(git log -n 1 --format=%H | head -n 1)" >> $GITHUB_OUTPUT
          echo "author_name=$(git log -n 1 --format=%an | head -n 1)" >> $GITHUB_OUTPUT
          echo "author_email=$(git log -n 1 --format=%ae | head -n 1)" >> $GITHUB_OUTPUT
      - name: Build and push
        id: build_push
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          file: ${{ inputs.path }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
