name: Build kvstore
on:
  workflow_dispatch:
    inputs:
      tags:
        description: "tags"
        required: true
        type: string
        default: v0.0
  push:
    tags:
      - 20[0-9]+-[0-9]+-[0-9]+
jobs:
  build:
    uses: ./.github/workflows/dockerfiles.yaml
    with:
      image: ingkle/kvstore
      path: ./dockerfiles/dockerfile
      build_runner: self-hosted
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
